export const getInitialNodes = (onElementRemove) => {
  return initialNodes.map((node) => ({
    ...node,
    data: {
      ...node.data,
      onElementRemove,
    },
  }));
};

const initialNodes = [
  {
    id: "blnk0",
    type: "blankNode",
    sourcePosition: "right",
    data: { label: null, color: "Connecting" },
    position: { x: -230, y: 432 },
  },
  {
    id: "b1a",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Research", color: "#655DFC" },
    position: { x: 0, y: 150 },
  },
  {
    id: "b2b",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "External", color: "#655DFC" },
    position: { x: 250, y: 110 },
  },
  {
    id: "b2c",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Internal", color: "#655DFC" },
    position: { x: 250, y: 190 },
  },
  {
    id: "b3d",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "B2C", color: "#655DFC" },
    position: { x: 500, y: 60 },
  },
  {
    id: "b3e",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "B2C", color: "#655DFC" },
    position: { x: 500, y: 140 },
  },
  {
    id: "b4f",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Online", color: "#655DFC" },
    position: { x: 750, y: -50 },
  },
  {
    id: "b4g",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Interview", color: "#655DFC" },
    position: { x: 750, y: 10 },
  },
  {
    id: "b4h",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Public Data", color: "#655DFC" },
    position: { x: 750, y: 70 },
  },
  {
    id: "b4i",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Health", color: "#655DFC" },
    position: { x: 750, y: 130 },
  },

  {
    id: "s1a",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Planning", color: "#82b3e8" },
    position: { x: 0, y: 290 },
  },
  {
    id: "s2b",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "PRD", color: "#82b3e8" },
    position: { x: 250, y: 250 },
  },
  {
    id: "s2c",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Specs", color: "#82b3e8" },
    position: { x: 250, y: 330 },
  },

  {
    id: "o1a",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Designing", color: "#e86443" },
    position: { x: 0, y: 430 },
  },
  {
    id: "o2b",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Hardware", color: "#e86443" },
    position: { x: 250, y: 390 },
  },
  {
    id: "o2c",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Software", color: "#e86443" },
    position: { x: 250, y: 470 },
  },

  {
    id: "p1a",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Manufacturing", color: "#e8909c" },
    position: { x: 0, y: 570 },
  },
  {
    id: "p2b",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Material", color: "#e8909c" },
    position: { x: 250, y: 530 },
  },
  {
    id: "p2c",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Production", color: "#e8909c" },
    position: { x: 250, y: 610 },
  },

  {
    id: "v1a",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Sales/Marketing", color: "#a683eb" },
    position: { x: 0, y: 710 },
  },
  {
    id: "v2b",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Online", color: "#a683eb" },
    position: { x: 250, y: 670 },
  },
  {
    id: "v2c",
    type: "customNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Dealership", color: "#a683eb" },
    position: { x: 250, y: 750 },
  },
];

export default initialNodes;
