
const initialNodes = [
  {
    id: "b1a",
    type: "coloredNode",
    sourcePosition: "right",
    data: { label: "Research" },
    position: { x: 0, y: 150 },
  },
  {
    id: "b2b",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "External" },
    position: { x: 250, y: 110 },
  },
  {
    id: "b2c",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Internal" },
    position: { x: 250, y: 190 },
  },
  {
    id: "b3d",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "B2C" },
    position: { x: 500, y: 60 },
  },
  {
    id: "b3e",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "B2C" },
    position: { x: 500, y: 140 },
  },
  {
    id: "b4f",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Online" },
    position: { x: 750, y: -50 },
  },
  {
    id: "b4g",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Interview" },
    position: { x: 750, y: 10 },
  },
  {
    id: "b4h",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Public Data" },
    position: { x: 750, y: 70 },
  },
  {
    id: "b4i",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Health" },
    position: { x: 750, y: 130 },
  },

  {
    id: "s1a",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Planning" },
    position: { x: 0, y: 290 },
  },
  {
    id: "s2b",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "PRD" },
    position: { x: 250, y: 250 },
  },
  {
    id: "s2c",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Specs" },
    position: { x: 250, y: 330 },
  },

  {
    id: "o1a",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Designing" },
    position: { x: 0, y: 440 },
  },
  {
    id: "o2b",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Hardware" },
    position: { x: 250, y: 400 },
  },
  {
    id: "o2c",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Software" },
    position: { x: 250, y: 500 },
  },

  {
    id: "p1a",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Manufacturing" },
    position: { x: 0, y: 600 },
  },
  {
    id: "p2b",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Material" },
    position: { x: 250, y: 550 },
  },
  {
    id: "p2c",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Production" },
    position: { x: 250, y: 650 },
  },

  {
    id: "v1a",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Sales/Marketing" },
    position: { x: 250, y: 650 },
  },
  {
    id: "v2b",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Online" },
    position: { x: 250, y: 650 },
  },
  {
    id: "v2c",
    type: "coloredNode",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Dealership" },
    position: { x: 250, y: 650 },
  },
];

  export default initialNodes;